### ISSUE TITLE
Form security plan for storing sensitive credentials in Github Secrets

### ISSUE THREAD

**Issue by jonathansmolenski** [unity-sds/unity-cs#1]
Provide:
* An outline of how we are storing sensitive information.  
* Who will have access? 
* Who can implement it?
* How can it be updated?
* What encryption tech/tools, etc.. will be used?

**Comment by galenatjpl** [comment]
Still need a little documentation on this, on the wiki

**Comment by galenatjpl** [comment]
Still need to put documents for the security plan in an accessible location

**Comment by jonathansmolenski** [comment]
https://github.com/unity-sds/unity-cs/wiki
