### ISSUE TITLE
Attach Policies to our OIDC Role

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#115]
1).  Attach EC2, EKS, API Gateway policies to the OIDC role.
2).  Prove the GH actions works on those components.

**Comment by galenatjpl** [comment]
@jonathansmolenski what is the MCP ticket for this?

**Comment by jonathansmolenski** [comment]
I followed up with MCP's support desk on this, it had fallen through the cracks. 
 
 We got the policies attached and updated the AMI ids to use golden AMIs, and now Unity-SPS's demo branch deploys over OIDC properly.  The job is described as "Deployment OIDC" in the unity-cs-infra repository
