### ISSUE TITLE
Implement API Gateway tweaking into a script

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#116]
Instead of doing manual setup/mods, there should be a script to automate some of the API Gateway things:

1) setting up and API gateway -- DONE
2) attaching services to gateway. -- DONE
3) **OPTIONAL FOR NOW:**  modifications to gateway (e.g. incremental adding/modifying routes, without trashing the whole set of routes)

Most likely the above would be handled in a Terraform script. 

This will enable more to be part of the overall automation workflows.

**Comment by ramesh-maddegoda** [comment]
Implemented terraform to deploy the API Gateway. The source code is available at https://github.com/unity-sds/unity-cs/tree/api-gateway-terraform/terraform/terraform-api-gateway

**Comment by galenatjpl** [comment]
Future work (23.2) is covered in https://github.com/unity-sds/unity-cs/issues/207

**Comment by galenatjpl** [comment]
closing, since rest of this work is in 23.2
