### ISSUE TITLE
Nightly SSM/TF param management + flow

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#132]
Nightly Flow + SSM param population + deployment : 

 static JSON (GHA) --> run GH action --> (populate SSM with high-level) --> generate terraform vars --> deploy (tf apply) --> populate specific/final SSM params

Acceptance Critieria:
- [x] High-level SSM params get populated with deployment
- [ ] SSM params get torn down with nightly
- [x] TF state files get populated in bucket
- [x] EKS state gets populated in S3 bucket
- [ ] Teardown blows away TF state in S3
- [ ] SSM params are being tracked as source control (nightly.yml)

**Comment by buggtb** [comment]
Lets go through these open checkboxes @galenatjpl  

SSM params get torn down with nightly - This will occur is someone runs terraform destroy on the environment provisioner stuff, although if things are set outside of the terraform domain, they will persist. Considering we'll over write them anyway I think this is both taken care of else where and lacking any consequence even if they remained. I guess the person writing the nightlies could write a script to purge them all, but I'd only do that in an account where only the nightlies are deployed cause you'll have a lot of sad people if its a general use account.

 EKS state gets populated in S3 bucket - Not entirely sure what this means, eks is managed by eksctl which uses cloudformation not s3 to manage state.
 
 Teardown blows away TF state in S3 - This is just how any terraform destroy process works, again though, you could script it just to remove anything from S3, that should go with Jonathan's nightly if you really want to do that.

SSM params are being tracked as source control (nightly.yml) - This is in part what we were discussing yesterday with @ryanhunter-jpl with somethings going into the management console.

**Comment by buggtb** [comment]
Unchecked items split out into single tickets to shut the ticket of doom

/close
