### ISSUE TITLE
Update API GW SSM Parameters when deploying API GW with terraform

### ISSUE THREAD

**Issue by ryanhunter-jpl** [unity-sds/unity-cs#189]

**Comment by ryanhunter-jpl** [comment]
Automated deployments of API GW and the projects that depend on it currently relies on manually created SSM Parameters. These SSM Parameters should instead be created/updated when API GW is deployed with terraform.

**Comment by ryanhunter-jpl** [comment]
Current change seems to work, waiting to talk to someone about the implementation details. Because of the difficulty of managing the state of the shared AWS accounts, I'm not sure we can do this very cleanly without more effort.

**Comment by galenatjpl** [comment]
@ryanhunter-jpl I think there is a discussion to be had about where the SSM for these values resides.  I'm thinking that this could reside in the project AWS account, and not necessarily in the shared AWS account.  I think the shared AWS account SSM could contain a single/lightweight pointer to the project SSM, but all of the hosts, ports, details, etc.. of the account can be in the account SSM.  Further discussion would be good here.

**Comment by ryanhunter-jpl** [comment]
SSM Parameters for the rest api id and authorizer id get created at project api gateway creation time. This enables services to register their routes with an authorizer on deployment.
