### ISSUE TITLE
Cognito Users Necessary for Unity-Sips-Test deployment

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#197]
As a necessary prerequisite to getting https://github.com/unity-sds/unity-project-management/issues/71 done, we want to make sure some **basic Cognito users** are in place to support the Unity-Test and Unity-Sips-Test accounts.

Acceptance Criteria:

- [ ] The necessary Cognito Users are deployed to Unity-Test, that will enable basic activities of the demo to occur.  @ramesh-maddegoda will probably have to consult with the SPS Team, and ADS Teams, at a minimum, to figure out what these users should be.
- [ ] Some basic documentation exists, in Gitbook, describing what the users are.

**Comment by ramesh-maddegoda** [comment]
Cognito User Standards
https://github.com/unity-sds/unity-cs/wiki/Cognito-User-Standards

**Comment by galenatjpl** [comment]
Users added and this is a manual step anyway.  Closing ticket.
