### ISSUE TITLE
Implement API Gateway creation scripts/terraform

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#200]
This may already be implemented, but the API Gateway on the project account (e.g. Unity-Sips-Test) needs to be fully automated as part of a normal account deployment.

Acceptance Criteria:
- [x] Terraform scripts for API Gateway creation exist and are executable (by Management Console bootup)

**Comment by ryanhunter-jpl** [comment]
Terraform to do this has been merged in to unity-cs-infra. Next step is to add this automation as a GitHub action and incorporate in main account deployment action.

**Comment by ryanhunter-jpl** [comment]
Need MCP to add an iam:PassRole allow for API GW in order to incorporate in GitHub action. [Ticket created](https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-2069). Something similar has already been done, so this shouldn't be blocked for long.

**Comment by ryanhunter-jpl** [comment]
MCP completed work on this ticket - resuming implementation. GitHub Action is currently working, now working on integrating the action with the main account deployment action.

**Comment by ryanhunter-jpl** [comment]
Successful deployment with API GW: https://github.com/unity-sds/unity-cs-infra/actions/runs/4887948443/jobs/8725121174

Successful API GW deployment: https://github.com/unity-sds/unity-cs-infra/actions/runs/4888396638/jobs/8726008637

**Comment by galenatjpl** [comment]
Implemented.
