### ISSUE TITLE
Roles as Code Takeover

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#216]
Ryan is taking over from John Mastron.

**Comment by ryanhunter-jpl** [comment]
Meeting with Gabe from MCP on Wednesday, copied relevant code and documentation as well as writing up additional guidelines for MCP to use John's solution for eks OIDC providers.

**Comment by galenatjpl** [comment]
Will be having a meeting with MCP on 6/7.

**Comment by galenatjpl** [comment]
We met and passed the code the MCP.  Closing this ticket.  MCP will follow-up on progress on their end.
