### ISSUE TITLE
Automate bringing up Management Console from EC2, using CloudFormation Script

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#221]
In order to "eat our own dogfood", the Nightly deployments/tests should bring up a new Unity Management Console (in the unity-sips-test account), as the first step in the series of nightly actions.

The rough order of operations would be as follows:

0) Populate SSM params that enable the nightly (VPC ID, AMI ID, instance type, subnet)

1) The "Nightly" action would run on a scheduled basis (i.e. nightly via cron)

2) The action would invoke the AWS CloudFormation API (no need to worry about AWS Partner Solutions yet) directly, over OIDC.

3) The CloudFormation stack (maintained by @pymonger) would run, and bring up an EC2 instance.  @pymonger has already implemented the ability to instantiate the Management Console EC2 [in this ticket](https://github.com/unity-sds/unity-on-demand/issues/26).

4) Teardown the EC2.

**PREREQUISITES:**
* It would be nice if https://github.com/unity-sds/unity-cs/issues/222 is completed, but it's not an absolute prerequisite.

**Acceptance Criteria:**
- [x] Verify that EC2/cron invokes CloudFormation, in a nightly manner (as described above)
- [x] Verify that the Management Console EC2 instance gets properly instantiated. (verify it's running)
- [x] Verify that at the end of this process, the EC2 is successfully torn down.

**REFERENCES:**
https://github.com/unity-sds/unity-on-demand-cloudformation/tree/develop/templates
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html

![Image](https://github.com/unity-sds/unity-cs/assets/47542238/d4c6ac2a-67cc-4ca5-96ea-7a55d9c43a10)

**Comment by jonathansmolenski** [comment]
We're missing a required permission for our oidc role, IAM:PassRole, so I've requested it in the 3 non-prod accounts here: https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-2283

**Comment by jonathansmolenski** [comment]
Looks like we're missing a delete permission as well.  Requested here: https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-2284

**Comment by galenatjpl** [comment]
Can't roll-back the stack due to the lack of the passRole permission.  Needed if it fails to spin up and/or in the tear-down step.

**Comment by galenatjpl** [comment]
pushing to 23.3 due to MCP delays

**Comment by jonathansmolenski** [comment]
MCP assigned us the passrole privileges and I tested them out.  The new issue is logged here:

https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-2326

**Comment by jonathansmolenski** [comment]
This is now working nicely under the nightly test scripts
