### ISSUE TITLE
Start getting the ball rolling on the EarthData Login process

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#23]

**Comment by ramesh-maddegoda** [comment]
Registered for an EarthData login.

**Comment by ramesh-maddegoda** [comment]
Registered personal EarthData Login profile in both production and UAT sites of the EarthData.
- https://urs.earthdata.nasa.gov/home (production)
- https://uat.urs.earthdata.nasa.gov/home (UAT)

**Comment by ramesh-maddegoda** [comment]
Tested user token creation, listing and deletion using the the RESTful APIs as explained in the following page.
https://urs.earthdata.nasa.gov/documentation/for_users/user_token

**Comment by ramesh-maddegoda** [comment]
Frequently Asked Questions (FAQ) of the EarthData Login is available  at  https://urs.earthdata.nasa.gov/documentation/faq

**Comment by ramesh-maddegoda** [comment]
**Integration applications to use EarthData Login**

In the following page, there is a list of topics related with the **EarthData Login Integration** under the section **Integration**
https://earthdata.nasa.gov/collaborate/open-data-services-and-software/api/earthdata-login-api 

The above page has following topics. However, it required to get access to view the following wiki pages.

**Integration**

- Apache URS Authentication Module
- Auto-Authorization
- Client Integration
- Earthdata Login Integration and Development Wiki
- How To Register An Application
- How to Set up ECHO type applications
- How To Use Tokens From Another Earthdata Login Application
- Implementing Earthdata Login SSO
- Javascript and CORS
- SSO Overview
- User Profile Information
- Working With The Earthdata Login API
 

In addition, the EarthData Login policy is available at: https://earthdata.nasa.gov/esdis/esdis-policy/earthdata-login-policy
