### ISSUE TITLE
Introduce a lambda variable that can store a CSV of role Strings that are allowed

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#287]
This variable will store a list of strings that will be iterated over programmatically in the lambda authorizer function, instead of hard-coding something like ROLE1 || ROLE2 || ROLE3, etc..

Also modify the lambda to re-work the code to use the list variable.

Acceptance Criteria:
- [x] List variable created in IAC (terraform script)
- [x] lamdba code changed to use variable
- [x] tested out in a real deployment venue

**Comment by ramesh-maddegoda** [comment]
- An environment variable called COGNITO_GROUPS_ALLOWED was introduced in lambda authorizer.
- The environment variable can have the list of groups configured as a comma separated list (E.g.  Unity_Viewer, Unity-SBG-Dev-All-ReadOnly, Group_01, Group02).
- This implementation was successfully tested with the unity-cs-common-lambda-authorizer in Unity-SBG-Dev account.

**Related source code:**

Lambda Authorizer Code: https://github.com/unity-sds/unity-cs-auth-lambda/blob/f05c6067bc41e3760af9c4edf330f580007eacec/index.js#L73

Terraform: https://github.com/unity-sds/unity-cs-infra/blob/8c7f9ae87b1df55c3657f73ea9904f1c371684e8/terraform-project-api-gateway_module/main.tf#L104
