### ISSUE TITLE
Dockerize Nightly Environment to provide Selenium Support

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#290]
Needed for reproducible Selenium env.
Selenium puts out docker images that already has Selenium installed and configured.
As a goal, we don't want to be in the business of creating our own AMIs, give that MCP has the concept of their own "golden" images we have to use.

**Comment by galenatjpl** [comment]
complete

**Comment by jonathansmolenski** [comment]
This has been done, the transition to Unity-DEV to Unity-CM went very well through this process.
