### ISSUE TITLE
Create sequence diagram for basic deployment

### ISSUE THREAD

**Issue by jonathansmolenski** [unity-sds/unity-cs#3]

**Comment by galenatjpl** [comment]
Steps include:
- deploy A
- deploy B
- ... etc..
- smoke test / health check step

**Comment by galenatjpl** [comment]
@jonathansmolenski You already created this diagram (the one that showed the sequence of deploys, smoke tests, etc..).  Can you post this diagram in a place that makes sense in https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/common-services
, then close this ticket?

**Comment by galenatjpl** [comment]
I have uploaded the most recent version of the diagram, and will close this ticket.
