### ISSUE TITLE
Venue API Gateway (CS)

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#320]
This issue is all about setting up the venue API Gateway on the venue account, in the case `unity-SBG-Dev` account.
This is already in place, but just need to come up with a test case that proves this works (being accessed from the shared services API GW).

**Comment by ramesh-maddegoda** [comment]
### Steps to test the venue API Gateway and test results

1) Create 2 API Gateway resources as follows:

-   /demo-data - for unsecured resource
-   /demo-data-secured - for secured resource

2) Integrate both resources  with the example demo data URL: https://api.nasa.gov/neo/rest/v1/neo/browse?api_key=DEMO_KEY 

3) Secure /demo-data-secured by enabling Unity_CS_Common_Authorizer in the Method Request.

4) Deploy the API Gateway 

5) Access the /demo-data resource without a valid access token (this should show results)
<img width="1402" alt="Access-unsecufed-resource-without-token" src="https://github.com/unity-sds/unity-cs/assets/94033485/8485f034-e0bd-4f70-8e13-005fecb45d3c">


6) Access the -   /demo-data-secured resource without a valid access token (this should show “Unauthorized” response).
<img width="1410" alt="Access-without-token" src="https://github.com/unity-sds/unity-cs/assets/94033485/4cc6625b-aab5-424e-afd0-173ed617e6dc">

7) Get a valid access toke using one of the methods documented at https://github.com/unity-sds/unity-cs/wiki/Getting-Cognito-JWT-Tokens-in-Command-Line 

8) Access the -   /demo-data-secured resource with a valid access token (this should show results).
<img width="1375" alt="Access-secured-resource-with-token" src="https://github.com/unity-sds/unity-cs/assets/94033485/3b85866f-bfe0-42e8-a49a-c4ac194322a8">

**Comment by ramesh-maddegoda** [comment]
### Steps to test the shared services API Gateway and test results

9) Access the /demo-data resource through shared services API Gateway proxy without a valid access token (this should show results)

E.g: https://<api-gateway-id>.execute-api.us-west-2.amazonaws.com/prod/sbg/dev/demo-data

<img width="1362" alt="Access-unsecured-resource-through-shared-services-APIGW-without-token" src="https://github.com/unity-sds/unity-cs/assets/94033485/38589af8-d2f6-49a3-8727-258a3f3c9de5">

10) Access the /demo-data-secured resource through shared services API Gateway proxy without a valid access token (this should show "Unauthorized" response)

<img width="1406" alt="Access-secured-resource-through-shared-services-APIGW-without-token" src="https://github.com/unity-sds/unity-cs/assets/94033485/d161ae4f-64ec-488c-9578-b961390d9fb9">

11) Get a valid access toke using one of the methods documented at https://github.com/unity-sds/unity-cs/wiki/Getting-Cognito-JWT-Tokens-in-Command-Line

12) Access the /demo-data-secured resource through shared services API Gateway proxy with a valid access token (this should show data)

<img width="1404" alt="Access-secured-resource-through-shared-services-APIGW-with-token" src="https://github.com/unity-sds/unity-cs/assets/94033485/ed01339f-abe0-4568-8bd8-0b9326b170cc">
