### ISSUE TITLE
Integrate HTTPD into the Reference Application

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#352]
Blocker:  Cognito needs HTTPS endpoint for Management Console

**Comment by mike-gangl** [comment]
we have certs and domains, this should not be blocked any longer.

**Comment by rtapella** [comment]
"Reference application" is now the Management Console, right @galenatjpl  ?

**Comment by galenatjpl** [comment]
@rtapella Yes, the "reference application" is now the Management Console.  I'm also tagging @ramesh-maddegoda and @mike-gangl  here on this confirmation comment.

**Comment by galenatjpl** [comment]
We recently proved that the Management Console was able to come up and work within this structure. Closing this ticket, as it was proven to work.
