### ISSUE TITLE
Enable HTTPS in Management Console

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#355]
Might need to reach out to MCP about this.
Might need a valid SSL cert for this.

This is needed for issue #354 to work.

**Comment by mike-gangl** [comment]
We have the valid SSL cert, this should no longer be blocked

@rtapella and @jdrodjpl. We _do_ need a working httpd in the venues, which i think @ramesh-maddegoda is/can work on.

**Comment by galenatjpl** [comment]
@mike-gangl @jdrodjpl We think that there is probably NO change required at the level of the MC itself.  Just keeping this ticket open until @ramesh-maddegoda prototypes of the HTTPD communication to the MC proves that no change is necessary here.

**Comment by galenatjpl** [comment]
We decided that no change in the Management Console was necessary.   We think this ticket can be closed, but before doing so, @mike-gangl can you please confirm that the websocket stuff in the MC is working now?

**Comment by galenatjpl** [comment]
The websocket checking is being checked in another ticket.  Closing this one.
