### ISSUE TITLE
Figure out what the json reponse format is

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-cs#371]
Format is here (linked to manage changes):
https://github.com/unity-sds/unity-project-management/issues/101#issuecomment-2045802548

**Comment by rtapella** [comment]
see https://github.com/unity-sds/unity-project-management/issues/101

**Comment by rtapella** [comment]
Would like to see:

recent_healthy: stores the most recent timestamp of a HEALTHY response (same as “date” if status is HEALTHY)
Maybe : ”endpoint” or “source” to confirm what’s being checked?

Think about: Authorization- who owns the username/password for hitting an authenticated endpoint. Multiple components for a service area

future: historical records and tracking 'events'

**Comment by GodwinShen** [comment]
@rtapella any update on this ticket?  Per the plan it was slated to be complete in 24.2.1.  Seems like a low-hanging fruit
