### ISSUE TITLE
Update documentation to include necessary Cognito roles/users

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#372]
Update this page:
https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/deployment-concepts-and-infrastructure/detailed-breakdown-of-project-onboarding-steps

For example, I think new roles such as:

Unity-EMIT-global-project-team
Unity-EMIT-Dev-venue-team
Unity-SBG-global-project-team
Unity-SBG-Dev-venue-team

Following the convention:

Unity-<PROJECT>-global-project-team = Edge case where cross venue data stuff needs to occur
Unity-<PROJECT>-<VENUE>-venue-team = Access to all things in a venue account

are needed.

Review step 5, in particular, in the above docs, and make changes as necessary.

**Comment by ramesh-maddegoda** [comment]
Reviewed and updated the step 5 of https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/common-services/docs/users-guide/deployment/deployment-concepts-and-infrastructure/detailed-breakdown-of-project-onboarding-steps
