### ISSUE TITLE
Add SSM Parameter that identifies the shared services CloudFront distribution for a given venue

### ISSUE THREAD

**Issue by anilnatha** [unity-sds/unity-cs#375]
When the Management Console is deployed, a SSM parameter needs to be created that stores the CloudFront distribution of the shared services account tied to the current venue account.

This should be added to the script that creates the SSM params.

Idea:
create shared service SSM values that represent shared things (cloudfront, cognito, etc..), then have the deployer only select the shared services account ID, which will know where to go, to get the SSM values, then copy them into the venue SSM.

**Comment by galenatjpl** [comment]
@ramesh-maddegoda I added you to this ticket, because I think I need some guidance on how to get the appropriate value.

**Comment by galenatjpl** [comment]
@ramesh-maddegoda @mike-gangl @anilnatha @rtapella 
For this parameter, two things:
1) we should call it /unity/shared-services/cloudfront/distribution
2) We should be creating it according to [this guidance](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment)

Sound good?

**Comment by ramesh-maddegoda** [comment]
> @ramesh-maddegoda @mike-gangl @anilnatha @rtapella For this parameter, two things:
> 
> 1. we should call it /unity/shared-services/cloudfront/distribution
> 2. We should be creating it according to [this guidance](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment)
> 
> Sound good?

I think, that sounds good

**Comment by galenatjpl** [comment]
@anilnatha and/or @rtapella I think I need some more guidance on how this would be used, and what's expected here. I'm a bit confused.  Can you please provide an example?  This parameter would be created manually in the shared services account.  Also, is this needed anymore if the Nav bar is going to go through HTTPD (not cloudfront)?

**Comment by galenatjpl** [comment]
@anilnatha I think the way you describe it in your last post is now inaccurate.  @mike-gangl @ramesh-maddegoda and others have been pushing forward with an architecture that looks like this:
<img width="1406" alt="Screenshot 2024-06-03 at 9 54 28 AM" src="https://github.com/unity-sds/unity-cs/assets/47542238/5aaad23b-1315-4c25-87ad-fc8f30b3cf79">
So we should sync up, and meet to go over this architecture, and determine what is still needed on your part.

**Comment by anilnatha** [comment]
@galenatjpl Thank you for sharing this updated architecture diagram. This makes sense. Based on the diagram, it looks like the HTTPD service that I need to modify when deploying through marketplace is the _Venue_ HTTPD (shown on the right), not the shared HTTPD (shown on the left).

Going back to my original issue though, I would still need to inform Cognito of the URL that our application resides at. The domain portion of that is what I am stuck on. e.g. `dev.mdps.mcp.nasa.gov`, `test.mdps.mcp.nasa.gov`, etc. It it safe to say that I could construct the domain by following the formula `<venue>.<project>.mcp.nasa.gov`?

cc: @rtapella

**Comment by galenatjpl** [comment]
@anilnatha, No, it's not correct to use `<venue>.<project>.mcp.nasa.gov`.  The forms like `dev.mdps.mcp.nasa.gov`, `test.mdps.mcp.nasa.gov`, etc.. reference only the shared services type (dev or test in these examples).  Dev and test are concepts unrelated to project and venue.  I think the proper solution is to put the `dev.mdps.mcp.nasa.gov`, `test.mdps.mcp.nasa.gov`, etc.. value in a shared services SSM param, and you can access it from the venue, using the account ID, and [this guidance](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment).  

I went ahead and added a `/unity/shared-services/domain` shared SSM parameter in the `Unity-Dev` and `Unity-Test` and `Unity-Prod` shared service accounts, so you can use those, and that should suffice for this ticket. Please let me know if you want to discuss more.

**Comment by galenatjpl** [comment]
implemented, closing

**Comment by anilnatha** [comment]
@galenatjpl Thank you for closing the loop on this. To avoid cross account parameter reading (which requires multiple providers to be specified in our terraform. Could this SSM param be added to each project/venue account in addition to the shared service accounts?

**Comment by anilnatha** [comment]
@galenatjpl Also related, how are the ports for these handled. Notably, we're using port `4443` to access our service, and I honestly don't know if there are other ports in use, but regardless, I'd rather _not_ hard code this port in my terraform, but can do so for now.

**Comment by anilnatha** [comment]
@galenatjpl Kindly reminded me of [this example](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment#example-of-accessing-a-shared-ssm-value-from-a-venue-account) that showcases how we can access a shared services SSM parameter without the need to use another provider.

For now I'll continue to hard code the port number until Galen has had a chance to raise that with Ramesh.
