### ISSUE TITLE
Add SSM Parameter that identifies the cognito domain assigned to the respective user pool of a given venue

### ISSUE THREAD

**Issue by anilnatha** [unity-sds/unity-cs#376]
When the Management Console is deployed, a SSM parameter needs to be created that stores the cognito domain of a user pool of the shared services account tied to the current venue account.

This should be added to the script that creates the SSM params.

For example, the cognito domain for Unity-Test is `https://unitysds-test.auth.us-west-2.amazoncognito.com`

@galenatjpl This may need to be revisited if authentication does change to where our HTTPD proxy is handling the authentication check and redirecting users to cognito automatically; however, apps would possibly still need to know the cognito domain to allow users to logout.

**Comment by galenatjpl** [comment]
@anilnatha @ramesh-maddegoda , we are starting to have quiet a few shared services values.  
I'm thinking that values that reference things in the shared services account will start with:
`/unity/shared-services/`

I'm thinking of naming this one (for this ticket):
`/unity/shared-services/cognito/domain`

**Comment by galenatjpl** [comment]
implemented in PR

**Comment by galenatjpl** [comment]
This ticket is already closed, but probably needs to be re-worked as a shared-services param according to [this guidance](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment)

**Comment by galenatjpl** [comment]
@mike-gangl I just moved the ticket from "done" back to "todo".  So I can continue work on this ticket, now, with the new guidance.

**Comment by galenatjpl** [comment]
@mike-gangl This is marked as done and closed, but is still on the dependencies board.  What is the procedure again, to clear it from the Dependencies board?
