### ISSUE TITLE
Clean up Unity-Test Cognito User Pools

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#377]
It was discussed a while back that there are two cognito pools in the Unity-Test shared services account.
I believe the decision was that one of them was valid, and the other one would be deleted to avoid confusion.
Please delete the one that we don't need.

![Image](https://github.com/unity-sds/unity-cs/assets/47542238/57ad9102-6395-48ef-a35a-82a52663a17f)

**Comment by ramesh-maddegoda** [comment]
I deleted the unity-shared-services-user-pool which had only few users.
