### ISSUE TITLE
Create Monitoring S3 bucket upon Management Console deployment

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#380]
Create the S3 bucket during the course of venue deployment (most likely in run script).
In the same code, create the SSM parameter that holds the bucket name (https://github.com/unity-sds/unity-cs/issues/370)

**Comment by galenatjpl** [comment]
@hargitayjpl and @galenatjpl decided that we should probably re-use the S3 bucket already created by the Management Console. So re-work this this ticket to reflect that, or close this ticket.

**Comment by hargitayjpl** [comment]
We decided to reuse the S3 Bucket that is being created by the Management Console. 

Closing Ticket
