### ISSUE TITLE
Create Backend API method and API GW route to Serve Landing pages of Deployed services in a proj/venue

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#382]
Backend API to serve UI links that the Navbar UI needs to display.
Should be served as a JSON response.

This API will:
1) Be implemented in the existing Go backend code/API area of the management console (https://github.com/unity-sds/unity-management-console)
2) Will be fronted by an API Gateway entry point that looks like: `https://unity.com/project/venue/endpoints`

Acceptance Criteria:
- [ ] Ticket for S3 bucket creation is complete : https://github.com/unity-sds/unity-cs/issues/380
- [ ] Ticket for S3 SSM parameter creation is complete : https://github.com/unity-sds/unity-cs/issues/370
- [ ] API Gateway setup gets created by the run.sh (deployment of a venue) chain of events
- [ ] MC API can be successfully queried via the API GW URL (the shared service API GW, proxying to the venue API GW), and returns landing page JSON that's stored in the S3 bucket.
- [ ] The UI/UX "UI Navbar" component is happily able to request this data via the MC API

**Comment by rtapella** [comment]
https://github.com/unity-sds/unity-sds-portal/issues/3

**Comment by GodwinShen** [comment]
@jdrodjpl ping for status.

**Comment by jdrodjpl** [comment]
Finalizing the API Gateway aspect of this (lots I've needed to learn about the Unity setup on that end). Hoping to have it done by today.

**Comment by rtapella** [comment]
@galenatjpl @jdrodjpl what is the status of the health endpoint?

**Comment by galenatjpl** [comment]
@rtapella @jdrodjpl We decided to re-use the same healthCheck endpoint for this purpose (landing pages) as well.

**Comment by galenatjpl** [comment]
@jdrodjpl @mike-gangl @rtapella @anilnatha .  We just had a conversation in the Unity status meeting.   Right now, there is an existing endpoint that returns the health status, component name, and endpoint URL.  So this is sufficient for now.  We will work with this for now (the dashboard will query this URL).  We will see how this approach goes, and if necessary, open future tickets.  For now, I think we have everything we need.
