### ISSUE TITLE
Populate the Shared Services DAPA API URL in a Venue Deployment

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#387]
Luca needs the following SSM param to be created upon venue creation:

/unity/shared-services/dapa/api-url

The naming will be different, and @mike-gangl is going to help think about the approach of how these get populated in Shared Services account.

U-CS would populate this value to the Venue AWS account, upon deployment, by looking at the value in the proper shared services account.

**Comment by mike-gangl** [comment]
We will pull these values from the shared service account at management console deployment time. something like this:

the SS_ACCT_ID will be provided as an input to the management console deployment scripts.

```
SS_ACCT_ID = aws ssm get-parameter --name "/unity/shared-services/aws/account"
DAPA_CLIENT_ID = aws ssm get-parameter --name "arn:aws:ssm:us-west-2:${SS_ACCT_ID}:parameter/unity/shared-services/dapa/client-id"
DAPA_API_URL = aws ssm get-parameter --name "arn:aws:ssm:us-west-2:${SS_ACCT_ID}:parameter/unity/shared-services/dapa/api-url"
```

**Comment by galenatjpl** [comment]
@LucaCinquini @drewm-jpl Please see what Mike said above.  This is what I'm proposing, but I have only tested this out via the command line.  We need to see if terraform supports sucking in SSM values from another account, using the approach in @mike-gangl 's comment above.

**Comment by LucaCinquini** [comment]
Yes it seems like a good approach.

**Comment by galenatjpl** [comment]
It works, I tested. For example: 
```
data "aws_ssm_parameter" "dapa_client_id" {
  name = "arn:aws:ssm:us-west-2:${SS_ACCT_ID}:parameter/unity/shared-services/dapa/client-id"
}
```

**Comment by mike-gangl** [comment]
Documentation on sharing those params here: https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment

**Comment by galenatjpl** [comment]
We decided upon the above approach, of having the ssm param exist in the shared services account.  It's already populated there now for DEV.  @ngachung (the U-DS Team) will ensure that the appropriate /unity/shared-services/dapa/api-url SSM param value is populated in the DEV, TEST, and PROD shared services accounts.  So given that, there is nothing else to do for this ticket at the venue level.
