### ISSUE TITLE
Determine how DAPA Client ID SSM param gets populated in Shared Services

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#388]
DAPA, setup on the Shared Services account will have a client ID, that SPS deployments on venue accounts need.

One proposal is to 
1) have a SSM parameter convention (e.g. parameters starting with `/unity/shared-services/...`) on the shared services account.
2) Someone or some process populates `/unity/shared-services/dapa/client-id` on the Shared services account.
3) U-CS deployment script determines what Shared Services account a deployment is tied to, and queries the shared services SSM params starting with `/unity/shared-services`, and copies them as parameters into the venue account.

See:  https://github.com/unity-sds/unity-cs/issues/386

@mike-gangl said he was going to think some more about how step 2 above would work.

**Comment by mike-gangl** [comment]
We will pull these values from the shared service account at management console deployment time. something like this:

the SS_ACCT_ID will be provided as an input to the management console deployment scripts.

```
SS_ACCT_ID = aws ssm get-parameter --name "/unity/shared-services/aws/account"
DAPA_CLIENT_ID = aws ssm get-parameter --name "arn:aws:ssm:us-west-2:${SS_ACCT_ID}:parameter/unity/shared-services/dapa/client-id"
DAPA_API_URL = aws ssm get-parameter --name "arn:aws:ssm:us-west-2:${SS_ACCT_ID}:parameter/unity/shared-services/dapa/api-url"
```

**Comment by mike-gangl** [comment]
https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/common-services/docs/users-guide/deployment/shared-services-deployment

**Comment by galenatjpl** [comment]
Thanks @mike-gangl  for putting that guide together!  I tested that approach (e.g. resource pool, sharing to account, etc..) out a few days ago, and it seemed to work.  My only concern is support for Terraform accessing the variable, as I have not had time to test that out yet..

**Comment by mike-gangl** [comment]
@galenatjpl I think you tested this out, so i think we're good to close this ticket (?)

**Comment by galenatjpl** [comment]
@mike-gangl closing, just like https://github.com/unity-sds/unity-cs/issues/389
