### ISSUE TITLE
Determine how DAPA API URL SSM param gets populated in Shared Services

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#389]
DAPA, setup on the Shared Services account will have an API URL, that SPS deployments on venue accounts need.

One proposal is to 
1) have a SSM parameter convention (e.g. parameters starting with `/unity/shared-services/...`) on the shared services account.
2) Someone or some process populates `/unity/shared-services/dapa/api-url` on the Shared services account.
3) U-CS deployment script determines what Shared Services account a deployment is tied to, and queries the shared services SSM params starting with `/unity/shared-services`, and copies them as parameters into the venue account.

See:  https://github.com/unity-sds/unity-cs/issues/387

@mike-gangl said he was going to think some more about how step 2 above would work.

**Comment by mike-gangl** [comment]
Since this is a one time thing (we won't have many of these) i'm fine with a manual process. We should create a 'shared service' setup guide as well that includes this information.

**Comment by mike-gangl** [comment]
@galenatjpl I think you tested this out, so i think we're good to close this ticket (?)
