### ISSUE TITLE
Properly namespace the Management Console URL SSM parameter

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#398]
There is a `/unity/cs/management/httpd/loadbalancer-url` SSM param that gets created by the `unity-proxy` marketplace item, that gets run in the Management console bootstrap.go.  This param needs to be changed to be name-spaced with ${PROJECT}/${VENUE}.

So, for example 
`/unity/${PROJECT}/${VENUE}/management/httpd/loadbalancer-url`

Without this namespacing, bad things happen, like this SSM param being deleted when an arbitrary management console is destroyed.

See the following code:

https://github.com/unity-sds/unity-management-console/blob/5d9d326562c7daea8716ad88e9f4383edd9b3081/backend/internal/processes/bootstrap.go#L172

See also the following code:

https://github.com/unity-sds/unity-cs-infra/blob/54077b81679e929cac7daabc0b1e214f60a404ca/nightly_tests/run.sh#L218-L220

https://github.com/unity-sds/unity-cs-infra/blob/54077b81679e929cac7daabc0b1e214f60a404ca/nightly_tests/run.sh

https://github.com/unity-sds/unity-cs-infra/blob/54077b81679e929cac7daabc0b1e214f60a404ca/nightly_tests/uninstall_aws_resources_mc.py#L86

It seems to get set here:
https://github.com/unity-sds/unity-proxy/blob/84fd862bdca43318537262fb64e4f630801541ca/terraform-unity/networking.tf#L53

**Comment by GodwinShen** [comment]
@galenatjpl and @hargitayjpl ping for status.

**Comment by hargitayjpl** [comment]
```
data "local_file" "unity_yaml" {
  filename = "/home/ubuntu/.unity/unity.yaml"
}
locals {
  unity_config = yamldecode(data.local_file.unity_yaml.content)
  project      = local.unity_config.project
  venue        = local.unity_config.venue
}

resource "aws_ssm_parameter" "mgmt_endpoint" {
  name = "/unity/${local.project}/${local.venue}/management/httpd/loadbalancer-url"
  type = "String"
  value = "${aws_lb_listener.httpd_listener.protocol}://${aws_lb.httpd_alb.dns_name}:${aws_lb_listener.httpd_listener.port}/management/ui"
  overwrite = true
}
```
In order to namespace the SSM parameter I grabbed the `unity.yaml` MC config file and brought all the variables into terraform, so the variable can be used in the SSM parameter name.

I created a new `unity-proxy` version `0.14` that has the changes.

Also changed the `run.sh` in our `unity-cs-infra` repo to grab the newly updated MC URL 
`export SSM_MC_URL="/unity/${PROJECT_NAME}/${VENUE_NAME}/management/httpd/loadbalancer-url"
`

I tested all the above changes in unity-venue-dev


```
module.YBUYfM-unity-proxy-PmwGz.aws_ssm_parameter.mgmt_endpoint: Creation complete after 0s [id=/unity/hargitay/dev02/management/httpd/loadbalancer-url]
```

Eveything worked and has been pushed to main
