### ISSUE TITLE
move proxy lambda SSM param to venue/project namespace

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#401]
Need to rework the SSM parameter for the lambda to call to add a proxy path. I think this is already populated (e.g. /unity/cs/management/proxy/CggBwz-httpd-lambda-name, but it's not "knowable" without being told what it is. this should follow the format /unity/${PROJECT}/${VENUE}/cs/management/proxy/lambda-name

**Comment by mike-gangl** [comment]
PR for the fix to http-proxy is here: https://github.com/unity-sds/unity-proxy/pull/1

**Comment by mike-gangl** [comment]
After this is merged, we'll need to create a release and then update the marketplace entry to point at the newest release, as well as the management console to install a specific version (currently .12)
