### ISSUE TITLE
Create EC2 HTTPD Dev Server in Unity-venue-dev

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#404]
Manually create httpd EC2 Ubuntu server on Unity-VENUE-DEV account. This will provide a streamlined way to develop and test VENUE httpd changes (instead of the ECS way, which can be complicated and time-consuming).  

Create a set of instructions that tells how one can 
1) deploy the EC2 server to a venue account, 
2) make changes to the configuration, 
3) restart httpd so that the changes take effect.

NOTE:  This is item "2" on our U-CS HTTPD punch list

**Comment by mike-gangl** [comment]
@ramesh-maddegoda i hope to have this done today- anything I can help with?

**Comment by galenatjpl** [comment]
@ramesh-maddegoda, to update this ticket with notes from your slack message, we now have: 
* an EC2 instance running in the venue, hosting httpd (ucs-venue-httpd-server)
* a load balancer (ALB)
* a path to JupyterHub: http://ucs-httpd-alb-651291493.us-west-2.elb.amazonaws.com:8080/hub
* a route from https://www.dev.mdps.mcp.nasa.gov:4443/hub as follows:
 https://www.dev.mdps.mcp.nasa.gov:4443/hub   -> http://ucs-httpd-alb-651291493.us-west-2.elb.amazonaws.com:8080/hub - > JupyterHub in Venue Dev (We get login screen from Cognito. We have to modify the redirect URL of JupyterHub. The JupyterHub spawn is still failing and I am checking it).
 
 So I think what's left to do is this?
 1) document how you set this up in a quick step-by-step procedure in gitbook.
 2) document how one can make a change to the configuration and restart httpd (also in same place, in gitbook).
 3) Optionally share the PEM file over LFT, so that other team members can ssh into EC2 (or if SSM connect works, then that is not necessary)

We don't have to actually move the configurations from the EC2 to ECS as part of this ticket.  That can be done later, and we can work with @jpl-btlunsfo on that part.

So please let me know when the rest of this ticket is complete.  Thanks

**Comment by ramesh-maddegoda** [comment]
@galenatjpl , I documented all the steps at https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/common-services/docs/developers-guide/httpd-server-deployment 

Also, Session Manger options works to access this EC2 instance.

**Comment by ramesh-maddegoda** [comment]
Closed with completion.
