### ISSUE TITLE
Create Venue JupyterHub HTTPD config/rewrite rules

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#406]
On the VENUE HTTPD:  Modify the rewrite rules and any needed configuration in the venue (EC2) HTTPD for JupyterHub. After all this is done, a full test of JuptyerHub access should be performed.

NOTE: this is item "3b" on the 24.2 U-CS HTTPD punch list

Blocked by:

- [x] https://github.com/unity-sds/unity-cs/issues/404

**Comment by ramesh-maddegoda** [comment]
Today we tested the JupyterHub access through both Shared Services and Venue httpd. The connection is from shared services httpd - > venue httpd - > JupyterHub

1) The Cognito login screen appeared as a result of mod_auth_openidc
<img width="1522" alt="Screenshot 2024-05-29 at 5 26 27 PM" src="https://github.com/unity-sds/unity-cs/assets/94033485/290d14e8-d1dc-42a8-a974-384fcf787ebe">

2) After login the JupyterHub loaded as expected.
<img width="1481" alt="Screenshot 2024-05-29 at 5 26 56 PM" src="https://github.com/unity-sds/unity-cs/assets/94033485/74ff1711-f477-4c60-b3b7-2761c0640ba8">
<img width="1338" alt="Screenshot 2024-05-29 at 5 27 21 PM" src="https://github.com/unity-sds/unity-cs/assets/94033485/feaaa0fd-8868-46f7-aecf-a99d5cf3fc84">

**Comment by ramesh-maddegoda** [comment]
During the meeting today we checked this and noticed that other features are working except the web sockets.  It was decided to close this ticket and separately fix the web sockets.
