### ISSUE TITLE
Add common SSM param to venue for the AWS region

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#407]
In addition to /unity/shared-services/aws/account can we also include /unity/shared-services/aws/region ?

This should be added as a common SSM param in the script.

**Comment by hargitayjpl** [comment]
https://github.com/unity-sds/unity-cs-infra/blob/d4eb01f28f20c4d50b3e6843b0780d579395a7fc/nightly_tests/set_common_ssm_params.sh#L241-L246
```
#
# SSM:  /unity/shared-services/aws/account/region
# 
ACCOUNT_REGION_SSM="/unity/shared-services/aws/account/region"
ACCOUNT_REGION_VAL=$(aws ec2 describe-availability-zones --query "AvailabilityZones[0].RegionName" --output text)
refresh_ssm_param "${ACCOUNT_REGION_SSM}" "${ACCOUNT_REGION_VAL}" "account" "na" "aws" "unity-all-cs-processing-sharedServicesAwsAccountRegion"
```
