### ISSUE TITLE
Make API Gateway name dynamic, not hardcoded to SampleProject

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#408]
https://github.com/unity-sds/unity-cs-infra/blob/51c906c7f6a426c97e16cde0510c1c39dd2e041d/terraform-project-api-gateway_module/variables.tf#L44

use project and venue variables in name, instead

**Comment by hargitayjpl** [comment]
https://github.com/unity-sds/unity-cs-infra/blob/4f2890b01819b5e09b8ce9096d50bbe137c131f0/terraform-project-api-gateway_module/main.tf#L3
