### ISSUE TITLE
Determine how to access Cognito user pool in SS account from Venue account

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#410]
@anilnatha showed us code and a related error message where his terraform was trying to access Cognito resources in the shared services account.  He created an extra terraform provider block, but was still getting the error.  
One thought was that we need to set up some sort of cross-account permissions.

For example:
```
provider "aws" {
  alias = "source_account"
  assume_role {
    role_arn = "arn:aws:iam::SOURCE_ACCOUNT_ID:role/CrossAccountCognitoAccess"
  }
}

resource "aws_cognito_user_pool_client" "example" {
  provider = aws.source_account

  user_pool_id = "USER_POOL_ID"
  client_name  = "example-client"

  # other configuration settings
}
```

Another thought was that we could use a `profile` syntax instead.

So this need investigation to un-stick Anil.

**Comment by galenatjpl** [comment]
@anilnatha can you please post your error message, and perhaps an example terraform here, for reference?

**Comment by anilnatha** [comment]
@galenatjpl Sure!

Here is the error I see when I try to apply the terraform for cognito:

```
aws_cognito_user_pool_client.userpool_client: Creating...
╷
│ Error: creating Cognito User Pool Client (dn-unity-ui-unity-ui-client)
│ 
│   with aws_cognito_user_pool_client.userpool_client,
│   on cognito.tf line 6, in resource "aws_cognito_user_pool_client" "userpool_client":
│    6: resource "aws_cognito_user_pool_client" "userpool_client" {
│ 
│ ResourceNotFoundException: User pool us-west-2_yaOw3yj0z does not exist.
```

`cognito.tf`:

```
resource "aws_cognito_user_pool_client" "userpool_client" {
  name = "${var.deployment_name}-unity-ui-client"
  user_pool_id = data.aws_ssm_parameter.cognito_user_pool.value
  access_token_validity = 60
  allowed_oauth_flows = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes = ["email", "openid", "profile"]
  auth_session_validity = 3
  callback_urls = ["https://www.dev.mdps.mcp.nasa.gov:4443/${var.project}/${var.venue}/dashboard"]
  enable_token_revocation = true
  explicit_auth_flows = ["ALLOW_REFRESH_TOKEN_AUTH", "ALLOW_USER_SRP_AUTH"]
  generate_secret = false
  id_token_validity = 60
  logout_urls = []    // todo: determine if logout urls are needed
  prevent_user_existence_errors = "ENABLED"
  refresh_token_validity = 30
  supported_identity_providers = ["COGNITO"]

  token_validity_units {
    // Valid values are: seconds | minutes | hours | days
    access_token  = "minutes"
    id_token      = "minutes"
    refresh_token = "days"
  }

  provider = aws.unity_dev
  
}
```

The line, `provider = aws.unity_dev` was my attempt at informing the resource to use our shared AWS account, not the project venue account by using the additional provider I added to my `main.tf` because the shared AWS account is where the cognito user pool exists.

```
provider "aws" {
  alias = "unity_dev"
  region = var.region
}
```

**Comment by anilnatha** [comment]
@galenatjpl Good news!

I was able to successfully create a Cognito User Pool Client using what William suggested by using the `profile` attribute to the shared services AWS account provider:

```
provider "aws" {
  alias = "unity_dev"
  region = var.region
  profile = "unity_dev"
}
```

My understanding of this is that the `alias` is only used internally by terraform, but the `profile` attribute is what links to the profile in `~/.aws/credentials`. Apologies @wphyojpl, I misunderstood what you were explaining during our tagup.

@galenatjpl: Now we have a new issue, how do devs configure multiple providers in their terraform for marketplace to use for their deployments. I think we should create a separate ticket to track that. 🤷🏽  In the resolution of that ticket we should keep in mind that providers are required to be specified when running terraform locally, so perhaps we can come up with a way that these providers can coexist for both local development/testing and marketplace deployments.

CC: @ramesh-maddegoda @rtapella

**Comment by galenatjpl** [comment]
Awesome!  Thanks @wphyojpl for the solution!   @anilnatha I'll create a different ticket for the multiple providers question.

**Comment by galenatjpl** [comment]
@anilnatha new ticket here:  https://github.com/unity-sds/unity-cs/issues/411

**Comment by mike-gangl** [comment]
i'm confused, i don't think we want the venues to create clients/pools automatically in the shared services. That user-pool id information should be a varaible. Cognito groups, clients, etc need to be created by the MMO team and passed in to the applications.

**Comment by anilnatha** [comment]
@mike-gangl The user-pool-id is a variable, but if an app needs to integrate with cognito, it needs an "app integration". The process of registering an app with Cognito creates a `clientId` for the app to use when authenticating with Cognito.
