### ISSUE TITLE
Rework Dev Proxy Topology & Configuration

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#416]
Tasks:
1) reconfigure shared services HTTPD proxy to point to "unity/dev" ALB that points to venue ECS httpd, instead of the current one that points to the venue EC2 httpd.
2) Take a look at the ECS httpd proxy and make sure the unity-proxy SSM-based configuration was properly auto-setup at MC bootstrap-time.
3) Check with team first, but deprecate and/or destroy the EC2-based httpd proxy server and associated target group, and associated ALB.
4) Test that a request successfully makes its way through the layers (SS DNS --> SS ALB --> SS HTTPD --> VENUE ALB --> VENUE HTTPD --> VENUE MC)

**Comment by jpl-btlunsfo** [comment]
.2 should have already happened with the MC deploy (it would actually fail, otherwise). Do you want me to check this for a specific "blessed" MC instance?

**Comment by galenatjpl** [comment]
@jpl-btlunsfo yeah, we just deployed a unity/dev "blessed" instance.  You could check for that one.  Thanks

**Comment by galenatjpl** [comment]
This stuff got done, and we will be opening one more ticket to move the ECS (HTTPD) cluster into a private subnet.
