### ISSUE TITLE
SSM configuration modification for MC deployments

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#417]
It seems that we need to make the following updates to SSM params, in order for a new deployment to work in a new venue:

`/unity/cs/routing/venue-api-gateway/cs-lambda-authorizer-cognito-client-id-list`
need to set to “n/a” or something like that, automatically in the scripts, upon deployment, since Ramesh’s new lambda auth approach doesn’t need client IDs anymore (the new approach is based on cognito user pool ID only).
probably just need to hard-code this to “n/a” in the set_common_ssm_params.sh script, to make sure it gets set to something

`/unity/cs/routing/venue-api-gateway/cs-lambda-authorizer-cognito-user-pool-id`
this value is needed by the lambda auth code, so we need to set it.  Currently in unity-venue-dev it is set to a value of test , but that’s just plain wrong. Setting it to test allows for the MC to deploy, but the API gateway won’t work correctly later on.  So this needs to be set to a valid value.  I’m thinking the best approach is to create a shared services SSM param, and have it read from there.  So we need to :
create a shared services SSM param called /unity/shared-services/cognito/user-pool-id
update the code to get this instead, [here](https://github.com/unity-sds/unity-cs-infra/blob/8fd705e236423987b438e820c47a981dda84bbdc/terraform-project-api-gateway_module/main.tf#L69), using the ss account ID resource sharing approach

`/unity/cs/routing/venue-api-gateway/cs-lambda-authorizer-cognito-user-groups-list`
do basically the same for this, as the one above
create a shared services SSM param called /unity/shared-services/cognito/user-groups-list
update the code to get this instead, [here](https://github.com/unity-sds/unity-cs-infra/blob/8fd705e236423987b438e820c47a981dda84bbdc/terraform-project-api-gateway_module/main.tf#L74), using the ss account ID resource sharing approach

https://docs.google.com/spreadsheets/d/1_aoYW7-7Z-j6bsoiDlxPeiuCUzaWmR-Q7YlNeR79bKk/edit?gid=0#gid=0

Update the above SSM params in the sheet

**Comment by hargitayjpl** [comment]
https://github.com/unity-sds/unity-cs-infra/commit/724a1f220382445bf9bfcedf6cb724a69b838465
