### ISSUE TITLE
Implement shared services to dev proxy for SPS airflow endpoints

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#429]
In the SPS team meeting, we tried accessing the SPS endpoint via the shared services proxy.  This didn't seem to work.
Investigate this, and edit the httpd configurations as necessary to make this work.  

This ticket is for the Unity-Dev to Unity-Venue-Dev pathway only.

**Comment by galenatjpl** [comment]
@jpl-btlunsfo expects a PR on this, this week

**Comment by jpl-btlunsfo** [comment]
PR merged, this should be done!
