### ISSUE TITLE
Initiators: Move lambda logic into Airflow DAG

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#432]
remaining work:  move logic from lambda into airflow.  It would be a DAG evaluator. Per the ticket, the evaluation logs would be in one place (i.e. airflow), and the DAG-evaluation would allow for this. Operator can view everything in one place.   Related to Ticket 412

**Comment by drewm-jpl** [comment]
@galen, this is part of #412. Can we collapse this ticket into the existing work for #412?
