### ISSUE TITLE
Initiators: Schedule and Do Demo of CMR triggering

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#438]
Show a CMR trigger DEMO.

Do this after the work in https://github.com/unity-sds/unity-cs/issues/437 is complete.

Tentatively demo is on 8/13

**Comment by galenatjpl** [comment]
@GodwinShen and @mike-gangl is 8/13 an okay date for @pymonger to demo this?

**Comment by GodwinShen** [comment]
Sounds good to me.

**Comment by galenatjpl** [comment]
Demo is on 2024-08-13

**Comment by galenatjpl** [comment]
Demo completed.  CLosing..
