### ISSUE TITLE
Integrate MC HealthCheck API with Venue API Gateway

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#459]
This task is to integrate MC HealthCheck API with Venue API Gateway as a RESTful API. This also involves securing the MC HealthCheck API.

**Comment by galenatjpl** [comment]
@ramesh-maddegoda please add description to this ticket.

**Comment by galenatjpl** [comment]
After we deploy, the private NLB is created, but not connected to the API Gateway.  Still need to automate the connection of this via VPC Link.  @ramesh-maddegoda to add this automation to the scripts.

**Comment by ramesh-maddegoda** [comment]
Turned off EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic in NLB to resolve this.

Related PR: https://github.com/unity-sds/unity-cs-infra/pull/117
