### ISSUE TITLE
Research & Fix Cookies Piling Up Issue

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#466]
Research / Fix cookies issue that JupyterHub is encountering.
HTTP 401 error seen, with response size too large.

**Comment by galenatjpl** [comment]
@ramesh-maddegoda Is this a U-ADS issue, or an underlying networking issue that U-CS needs to address?  Also, can you please comment on the recent findings and/or any work left to do?

**Comment by ramesh-maddegoda** [comment]
@galenatjpl , I was unable to reproduce this issue with my previous attempts.

**Comment by galenatjpl** [comment]
@mike-gangl @mcduffie @wphyojpl .  I think we have a workaround, where @wphyojpl was able to manually delete cookies to get this to work.  Others (including me) are unable to reproduce this as well.  I'm going to close this issue since at least there is a workaround.  We spent a significant amount of time on this already.
