### ISSUE TITLE
Improve MC UI branch field

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#473]
It's unclear what the "branch" field is really for.  Make the UI understandable, and perhaps think about a default of `main`?  Again, not exactly sure how this value is used in the backend.
![Image](https://github.com/user-attachments/assets/d68bba13-b125-40d5-b5ed-8f2ea854b6f5)

**Comment by jdrodjpl** [comment]
Turns out, "branch" isn't even hooked up to anything. It's a form item that is never passed on. What, if anything, do we actually want this to be?
