### ISSUE TITLE
Deploy navbar/health-dashboard/mgmt-console as a base bootstrap-deploy

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-cs#483]
- once navbar is in the Marketplace, add it to the "new venue" bootstrap process along with the Management Console
- Navbar would be automatically available as part of the default deployments.
- Add entry to the marketplace YAML file:  https://github.com/unity-sds/unity-cs-infra/blob/main/nightly_tests/marketplace_config.yaml

- Additionally, what's needed is to add another method to the bootstrap.go code to support this item

**Comment by rtapella** [comment]
@galenatjpl so this can be closed?

**Comment by galenatjpl** [comment]
This is complete, and tested.
