### ISSUE TITLE
JupyterHub Integration into Unity Marketplace: Understand and Test Manual deployment as-is

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#489]
Understand what currently exists, and make sure you are able to manually execute the terraform code to deploy to a development venue.  This is a first step, before making any changes necessary for marketplace integration.

U-ADS has provided deployment instructions here:
https://github.com/unity-sds/unity-ads-deployment/blob/main/dev_env/README.md

According to @mcduffie , it's probably only necessary to run the JupyterHub (`dev_env/jupyterhub`) steps, and not the EFS or Cognito steps in development.  However, you should understand all of the necessary components, and think about what would be needed for a fresh install to a brand new venue.

**Acceptance Criteria:**
- [x] You understand what the IAC code does today, as-is
- [x] You are able to manually run the IAC to deploy JupyterHub to a dev venue
- [x] You are able to access what you deployed
- [x] You understand what the need is for the other components such as EFS and Cognito

**Comment by pymonger** [comment]
# Deploying the ADS from a Management Console instance

## Prerequisites

### Deploy a stack

Run through steps 11-13 as documented at https://unity-sds.gitbook.io/docs/mdps-overview/project-onboarding-procedure:

1. Connect to bastion host in the venue account, e.g. venue-dev:
   ```
   source ~/bin/update_mcp_creds-dev_venue.sh
   aws ssm start-session --target <instance ID>
   sudo su - ubuntu
   ```

1. Clone the `unity-cs-infra` repo:
   ```
   mkdir ~/.pymonger
   cd ~/.pymonger
   git clone https://github.com/unity-sds/unity-cs-infra.git
   ```

1. Run the stack creation:
   ```
   cd unity-cs-infra/nightly_tests
   export PROJECT=pymonger
   export VENUE=dev
   ./run.sh --destroy false --run-tests false --project-name $PROJECT --venue-name $VENUE
   ```
   Record the URL of the Management Console that get output to the screen when the `run.sh` command completes.
    
### Update the shared-services-httpd instance with your ALB

Run through steps 4 and 5 as documented at https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/maintenance/updating-venue-deployment.

1. In the venue account, log into the AWS dashboard and navigate to EC2 -> Load Balancers. Select your ALB which will be named according to the PROJECT and VENUE env variables exported above using this name convention:
   ```
   ${PROJECT}-${VENUE}-httpd-alb
   ```
   Copy the `DNS name` of the ALB.

1. Next log into the Shared Services account and find the `shared-services-httpd` instance in the EC2 console. Copy the instance ID.

1. Connect to the `shared-services-httpd` instance and navigate to the Apache HTTPD configuration you'll need to edit:
   ```
   source ~/bin/update_mcp_creds-dev.sh
   aws ssm start-session --target <instance ID>
   sudo su - ubuntu
   cd /etc/apache2/sites-enabled
   sudo vi unity-cs.conf
   ```

1. Add a block to the Apache HTTPD configuration to proxy requests to your ALB. Add a comment to clarify which PROJECT and VENUE it's for and paste in the ALB `DNS name` for the `VENUE_ALB_HOST` value, e.g.:
   ```
   # ----------
   # pymonger/dev
   #
   Define VENUE_ALB_HOST pymonger-dev-httpd-alb-xxxxxxxxx.us-west-2.elb.amazonaws.com
   Define VENUE_ALB_PORT 8080
   Define VENUE_ALB_PATH /pymonger/dev/
   RewriteEngine On
   RewriteCond %{HTTP:Connection} Upgrade [NC]
   RewriteCond %{HTTP:Upgrade} websocket [NC]
   RewriteCond %{REQUEST_URI} "${VENUE_ALB_PATH}"
   RewriteRule ${VENUE_ALB_PATH}(.*) ws://${VENUE_ALB_HOST}:${VENUE_ALB_PORT}${VENUE_ALB_PATH}$1 [P,L] [END]
   <Location "${VENUE_ALB_PATH}">
      ProxyPreserveHost on
      AuthType openid-connect
      Require valid-user

      # Added to point to httpd within the venue account
      ProxyPass "http://${VENUE_ALB_HOST}:${VENUE_ALB_PORT}${VENUE_ALB_PATH}"
      ProxyPassReverse "http://${VENUE_ALB_HOST}:${VENUE_ALB_PORT}${VENUE_ALB_PATH}"
      RequestHeader     set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
   </Location>
   ```

1. Restart Apache:
   ```
   sudo systemctl restart apache2
   ```

1. You should be able to access the Management Console at the following URL:
   ```
   https://www.<SS_PREFIX>.mdps.mcp.nasa.gov:4443/<PROJECT>/<VENUE>/management/ui
   ```
   where `SS_PREFIX` is `dev` for the dev venue.

### Add a user to the Cognito user pool and create app integration

1. In the Shared Services account, navigate to the Cognito console and view the `User pools`.

1. Select the `unity-user-pool` and you will be in the `Users` tab by default. Click on `Create user` to add your username to the pool if not there already.

1. Setup password once the confirmation email is sent.

1. Navigate to the `App integration` tab.

1. Copy the `Cognito domain` value, e.g.:
   ```
   https://xxx.auth.us-west-2.amazoncognito.com
   ```
   This will be needed when deploying jupyterhub via terraform.

1. Click on `Create app client`. Fill out the form accordingly:
   - App type: select `Public client`
   - App client name: use something descriptive, e.g. `uads-jupyter-venue-dev-pymonger-client`
   - Client secret: select `Generate client secret`
   - Authentication flows: select `ALLOW_CUSTOM_AUTH`, `ALLOW_REFRESH_TOKEN_AUTH`, and `ALLOW_USER_SRP_AUTH`
   - Accept default values for `Authentication flow session duration`, `Refresh token expiration`, `Access token expiration` and `ID token expiration`
   - Select `Enable token revocation` and `Prevent user existence errors`
   - Under `Hosted UI Settings`, specify the URL for the `Allowed callback URLs` section using the proxy URL configured in the previous section and this template:
     ```
     https://www.<SS_PREFIX>.mdps.mcp.nasa.gov:4443/<PROJECT>/<VENUE>/jupyter/hub/oauth_callback
     ```
     e.g.
     ```
     https://www.dev.mdps.mcp.nasa.gov:4443/pymonger/dev/jupyter/hub/oauth_callback
     ```
   - Specify the URL for the `Allowed sign-out URLs` section using the proxy URL configured in the previous section and this template:
     ```
     https://www.<SS_PREFIX>.mdps.mcp.nasa.gov:4443/<PROJECT>/<VENUE>/jupyter/hub/login/oauth_callback/logout
     ```
     e.g.
     ```
     https://www.dev.mdps.mcp.nasa.gov:4443/pymonger/dev/jupyter/hub/login/oauth_callback/logout
     ```
   - Accept default values for the rest and click `Create app client`.

1. Click on your created App client and under the `App client information`, record the `Client ID` nad `Client secret`. These will also be needed (in addition to the `Cognito domain`) when deploying jupyterhub via terraform.

### Run Core Setup on Management Console

1. In a browser, navigate to the Management Console using the URL you determined in the `Update the shared-services-httpd` section
   ```
   https://www.<SS_PREFIX>.mdps.mcp.nasa.gov:4443/<PROJECT>/<VENUE>/management/ui
   ```
   It may take a while for it to load up.

1. Log into it with the username and password you setup in the previous section.

1. Once it loads up, click on `Go!` under the `Core Management` section of the front page.

1. This will take you to a form. Accept the defaults and click on `Save`. This will open up a console and you should see some terraform output running there. Wait until it's completed.

## Deployment

### Provision shared storage on EFS

1. Connect to the MC instance in the venue account, e.g. venue-dev:
   ```
   source ~/bin/update_mcp_creds-dev_venue.sh
   aws ssm start-session --target <instance ID>
   sudo su - ubuntu
   ```

1. Clone the `unity-ads-deployment` repo:
   ```
   git clone https://github.com/unity-sds/unity-ads-deployment.git
   ```

1. Setup terraform variables:
   ```
   cd unity-ads-deployment/dev_env
   export PROJECT=pymonger
   export VENUE=dev
   cat > vars_jupyter.sh <<EOF
   #!/bin/bash
   export TF_VAR_project=${PROJECT}
   export TF_VAR_venue=${VENUE}
   export TF_VAR_venue_prefix="${PROJECT}-"
   export TF_VAR_efs_identifier="uads-${PROJECT}-${VENUE}-efs-fs"
   export TF_VAR_cognito_oauth_base_url="<Cognito domain>"
   export TF_VAR_cognito_oauth_client_id="<Client ID>"
   export TF_VAR_cognito_oauth_client_secret="<Client secret>"
   EOF
   chmod 755 vars_jupyter.sh
   ```
   Populate the `vars_jupyter.sh` script with the `Cognito domain`, `Client ID` and `Client secret` from the previous `Add a user to the Cognito user pool and create app integration` section.

1. Source the `vars_jupyter.sh` script:
   ```
   source vars_jupyter.sh
   ```

1. Run terraform:
   ```
   cd shared_storage
   terraform init
   terraform apply -auto-approve
   ```

### Provision Jupyterhub

1. Run terraform:
   ```
   cd ../jupyterhub
   terraform init
   terraform apply -auto-approve
   ```
