### ISSUE TITLE
Fill out remaining Security Guidelines doc items

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#50]
Filling out a few remaining sections, such as adding a few diagrams, adding some basic examples, and referencing U-SPS integration example.

**Comment by ramesh-maddegoda** [comment]
Completed the documentation on 01-Mar-2022 (https://github.com/unity-sds/unity-cs/wiki/Unity-Security-Guidelines). Also, added some code samples and relevant documents in the following locations.

- https://github.com/unity-sds/unity-cs-security/tree/main/code-samples/hysds_ui_auth
- https://github.com/unity-sds/unity-cs-security/tree/main/code-samples/hysds_mozart_mock
- https://github.com/unity-sds/unity-cs-security/tree/main/code-samples/hysds_mozart_mock_consumer
