### ISSUE TITLE
Terraform-driven Rebuild of Shared Services proxy to configure access to venue ALBs

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#504]
Build terraform to automate update of SS proxy. 
see also:  https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/maintenance/updating-venue-deployment

https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/developers-guide/httpd-server-deployment

https://stackoverflow.com/questions/63978548/how-to-run-scritps-after-create-ec2-using-terraform-during-apply

1) Create new EC2 Security group (reference ALB security group)

2) Create new shared-services-httpd EC2 instance

3) Populate proxy config from S3 bucket

4) Restart proxy service
 
5) Add new EC2 as a target to the ALB Target Group (group will now have 2 targets)

6) Remove old EC2 as a target from ALB Target Group (now there's only 1 target)

7) Destroy old shared-services-httpd EC2

Config File format check 
-s -T apache2ctl Status code

**Comment by galenatjpl** [comment]
@jpl-btlunsfo re-assigning to @hargitayjpl , as he is available to work on this now

**Comment by hargitayjpl** [comment]
**S3 Configuration Sync Implementation:**
- Set up S3 bucket ucs-ss-config to store master config files
- Developed sync_apache_config.sh script that:
    - ulls config from S3
    - Validates Apache configuration
    - Updates local config if changes detected
    - Restarts Apache service when needed
 
Prepared cron job for automated syncing (not implemented yet)
Status: Script tested in my environment.  Need to test in a prod environment
