### ISSUE TITLE
Provide documentation and working example of how security for a user logging into Jupyterhub would work

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#51]
This came up in a meeting, 

from Michael Gangl to Everyone:    1:52  PM
I think it would be helpful to work through some use cases that we're expecting with how this will work. For example, a user logging in to jupyterhub and making calls to the SPS

from Hook Hua to Everyone:    1:53  PM
+1 would help to ensure we cover both SSO and service-to-service API auth use cases

from Galen Hollins to Everyone:    1:54  PM
+1 Mike.  I will record this as a ticket, for us to provide a concrete use case and example

**Comment by ramesh-maddegoda** [comment]
A working example was created and successfully integrated Cognito authentication with JupyterHub. Working on the documentation.

**Comment by ramesh-maddegoda** [comment]
Documented the steps to integrate Amazon Cognito authentication with JupyterHub in the following wiki page.
https://github.com/unity-sds/unity-cs/wiki/Amazon-Cognito-Authentication-with-JupyterHub

Documented the approaches to get JWT Token in command line in the following wiki page. These approaches can be used in a Jupyter Notebook too.
https://github.com/unity-sds/unity-cs/wiki/Getting-Cognito-JWT-Tokens-in-Command-Line

**Comment by ramesh-maddegoda** [comment]
The issue [Create a working example for Jupyter Notebook users to access the protected WPS-T endpoints](url) will also create a working example related to this issue.
