### ISSUE TITLE
Secure HySDS (Mozart REST API + HySDS UI) in the U-SPS Demo

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#53]
Apply the same concepts that Ramesh secured in the reference example, to the actual U-SPS demo.

1. Configure AWS RESTful API Gateway to map with Mozart RESTful API.
2. Allow access to Mozart RESTful API only through the RESTful API Gateway (control access with AWS security groups).
3. Secure the "API Gateway mapped" Mozart endpoints with Cognito authentication.
4. Change the Mozart RESTful API URLs used in hysds_UI application to point to the API Gateway.
5. Update the ReactJS code of hysds_UI to obtain an access token from Cognito and access the Mozart endpoints protected by the API Gateway (this code is already implemented in our security code samples).

**Comment by galenatjpl** [comment]
@jonathansmolenski following up with @mgangl about access keys and their longevity. 
Permissions for EKS on JPL and MCP still needed.
@jonathansmolenski following up on help ticket for EKS permissions.

**Comment by ramesh-maddegoda** [comment]
Completed and merged changes to hysds_ui_with_auth/ with the following pull requests.

- [Add authorization header to REST API calls](https://github.com/unity-sds/hysds_ui_with_auth/pull/2)
- [Restructured the code to resolve missing Authorization headers in requests](https://github.com/unity-sds/hysds_ui_with_auth/pull/3)

The REST API Mozart related integration (with Authorizer) is available at https://github.com/unity-sds/unity-cs/blob/api-gateway-terraform/terraform/terraform-api-gateway/terraform-modules/api-gateway/unity-rest-api-gateway-oas30.yaml
