### ISSUE TITLE
Allow users to access protected WPS-T endpoint by Browser (Human based, interactive Auth)

### ISSUE THREAD

**Issue by ramesh-maddegoda** [unity-sds/unity-cs#76]
Allow users to access protected WPS-T endpoint by Browser (Human based, interactive Auth).

**Comment by galenatjpl** [comment]
Per @ramesh-maddegoda , the current blocker on this, is setting up JupyterHub.  In progess.

**Comment by ramesh-maddegoda** [comment]
I was able to setup JupyterHub on an AWS EC2 instance. Finally ,it worked after adding following configurations to the `jupyterhub_config.py` (generated with `jupyterhub --generate-config`).  Also please see the attached screenshots.

```
c.JupyterHub.hub_bind_url = 'http://0.0.0.0:8081'
c.JupyterHub.port = 80
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = 'jupyterhub/singleuser:latest'
```

![Screen Shot 2022-05-03 at 9.18.41 PM.png](https://images.zenhubusercontent.com/618d986498c9bb185f49e721/8884881c-f321-4323-86a3-d030c5334c3a)![Screen Shot 2022-05-03 at 9.18.46 PM.png](https://images.zenhubusercontent.com/618d986498c9bb185f49e721/2fc5853f-9c7b-40e4-a52e-05dc20a5b92b)![Screen Shot 2022-05-03 at 9.18.47 PM.png](https://images.zenhubusercontent.com/618d986498c9bb185f49e721/d086ce6c-65c3-47bb-94f0-8008bde79a80)![Screen Shot 2022-05-03 at 9.18.59 PM.png](https://images.zenhubusercontent.com/618d986498c9bb185f49e721/b7d3f2aa-82d9-49e1-9b42-0a74eb6265d9)![Screen Shot 2022-05-03 at 9.19.52 PM.png](https://images.zenhubusercontent.com/618d986498c9bb185f49e721/b5a9d4c1-06b2-4a5e-8232-6bf1034f89be)

**Comment by ramesh-maddegoda** [comment]
Working examples were created to access protected WPS-T endpoints from both a sample ReactJS App and a Jupyter Notebook.

Sample ReactJS Application with Cognito Authentication to Access WPS-T Endpoints
https://github.com/unity-sds/unity-cs-security/tree/main/code_samples/wpst/wpst_rest_consumer_ui

Wiki: Accessing Secured REST API Endpoints from Jupyter Notebook (using secured WPS-T endpoints as an example)
https://github.com/unity-sds/unity-cs/wiki/Accessing-Secured-REST-API-Endpoints-from-Jupyter-Notebook
