### ISSUE TITLE
Obtain JPL AWS EKS Permissions

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#84]
needed to deploy EKS cluster on JPL AWS, especially for use by U-AS and U-SPS.

**Comment by galenatjpl** [comment]
@jonathansmolenski This ticket probably has the highest priority currently, out of the tickets on your plate.  I think this is holding up deployment on JPL AWS by the U-SPS team.  U-SPS needs this capability soon.
Is there an open JPL cloud team request for this?

**Comment by jonathansmolenski** [comment]
I do have a JPL ticket for this, CLOUD-1777, which has been completed and the permissions need testing.  I'm working on that this week, hopefully to wrap it up.

**Comment by galenatjpl** [comment]
Related tickets:
https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/13/CLOUD-1777
https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/13/CLOUD-1833

**Comment by galenatjpl** [comment]
We got some permissions, but this still needs to be tested.  We have some terraform scripts we can use to test this.

**Comment by jonathansmolenski** [comment]
I need to get this working in an automated fashion so that I don't have to manually set things up

**Comment by galenatjpl** [comment]
We don't need EKS permissions anymore.  Focusing on MCP. Closing this issue
